version: '3'
services:
    php:
        # restart: always
        build: 
            args:
                user: 1000 # your username (echo $USER)
                uid: 1000 # your uid (id -u)
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - ./:/var/www/html
            - ./docker/php/prod.ini:/usr/local/etc/php/php.ini
        ports:
            - "9001:9001"
        environment:
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        networks:
          - laravel
    mysql:
        # restart: always
        image: 'mysql:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'laravelmysql:/var/lib/mysql'
        networks:
            - laravel
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
    nginx:
        # restart: always
        image: nginx:stable-alpine
        ports:
            - "80:80"
        volumes:
            - ./public:/var/www/html/public
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/logs:/var/log/nginx
        depends_on:
          - php
          - mysql
        networks:
          - laravel
    redis:
        # restart: always
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'laravelredis:/data'
        networks:
            - laravel
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
    # mailhog:
    #     # restart: always
    #     image: 'mailhog/mailhog:latest'
    #     container_name: mailhog
    #     ports:
    #         - '${FORWARD_MAILHOG_PORT:-1025}:1025'
    #         - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
    #     networks:
    #         - laravel
networks:
    laravel:
        driver: bridge
volumes:
    laravelmysql:
        driver: local
    laravelredis:
        driver: local
